"""add table Slclasses

Revision ID: 0002a0ba4674
Revises: c4f2f28a5d12
Create Date: 2023-05-18 00:37:12.140058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002a0ba4674'
down_revision = 'c4f2f28a5d12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
