"""add table Slclasses

Revision ID: 02aeb2f365cb
Revises: 51bb21e17e2d
Create Date: 2023-05-18 00:13:02.978839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02aeb2f365cb'
down_revision = '51bb21e17e2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slclass')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slclass',
    sa.Column('cdclass', sa.UUID(), autoincrement=False, nullable=False, comment='Ключь классов'),
    sa.Column('nmclass', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Наименование игрального класса'),
    sa.Column('full_nmclass', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Полное имя класса'),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True, comment='url для получения следующего обьекта класса'),
    sa.PrimaryKeyConstraint('cdclass', name='slclass_pkey')
    )
    # ### end Alembic commands ###
