"""add table Slclasses

Revision ID: 2e86a9b44ccf
Revises: 70a9a100ef93
Create Date: 2023-05-17 20:59:41.929303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e86a9b44ccf'
down_revision = '70a9a100ef93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('test_col', sa.UUID(), autoincrement=False, nullable=False, comment='Первичный Ключ'),
    sa.Column('test_name', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Test name'),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True, comment='url'),
    sa.PrimaryKeyConstraint('test_col', name='test_pkey')
    )
    # ### end Alembic commands ###
