"""fix alembic useng error

Revision ID: e46fbb40f3c7
Revises: 0f6bb09dd310
Create Date: 2023-05-20 23:30:08.210763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e46fbb40f3c7'
down_revision = '0f6bb09dd310'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slclass',
    sa.Column('cdclass', sa.UUID(), nullable=False, comment='Ключь классов'),
    sa.Column('nmclass', sa.String(), nullable=False, comment='Наименование игрального класса'),
    sa.Column('full_nmclass', sa.String(), nullable=True, comment='Полное имя класса'),
    sa.Column('url', sa.String(), nullable=True, comment='url для получения следующего обьекта класса'),
    sa.PrimaryKeyConstraint('cdclass')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slclass')
    # ### end Alembic commands ###
