"""add table Slclasses

Revision ID: 21e285a61f08
Revises: 88a190697653
Create Date: 2023-05-18 00:51:48.695763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e285a61f08'
down_revision = '88a190697653'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
