"""add table Slclasses

Revision ID: 23a3fb64496b
Revises: ce1a539bce22
Create Date: 2023-05-18 00:30:47.578879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a3fb64496b'
down_revision = 'ce1a539bce22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
