"""start app

Revision ID: d691fa4e4bc6
Revises: 640a33cb3b85
Create Date: 2023-03-30 21:40:04.944255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd691fa4e4bc6'
down_revision = '640a33cb3b85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test', 'test_col',
                    existing_type=sa.UUID(),
                    comment='Первичный Ключ',
                    existing_nullable=False)
    op.alter_column('test', 'test_name',
                    existing_type=sa.VARCHAR(),
                    comment='Test name',
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test', 'test_name',
                    existing_type=sa.VARCHAR(),
                    comment=None,
                    existing_comment='Test name',
                    existing_nullable=True)
    op.alter_column('test', 'test_col',
                    existing_type=sa.UUID(),
                    comment=None,
                    existing_comment='Первичный Ключ',
                    existing_nullable=False)
    # ### end Alembic commands ###
