"""start app

Revision ID: 640a33cb3b85
Revises: 
Create Date: 2023-03-30 21:36:41.949301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640a33cb3b85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('test_col', sa.UUID(), nullable=False),
    sa.Column('test_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('test_col')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
