"""add table Slclasses

Revision ID: 4d563e358169
Revises: 02aeb2f365cb
Create Date: 2023-05-18 00:20:40.717827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d563e358169'
down_revision = '02aeb2f365cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
