"""add table Slclasses

Revision ID: 51bb21e17e2d
Revises: 6cc4549df3de
Create Date: 2023-05-18 00:09:02.117235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51bb21e17e2d'
down_revision = '6cc4549df3de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slclass',
    sa.Column('cdclass', sa.UUID(), nullable=False, comment='Ключь классов'),
    sa.Column('nmclass', sa.String(), nullable=False, comment='Наименование игрального класса'),
    sa.Column('full_nmclass', sa.String(), nullable=True, comment='Полное имя класса'),
    sa.Column('url', sa.String(), nullable=True, comment='url для получения следующего обьекта класса'),
    sa.PrimaryKeyConstraint('cdclass')
    )
    op.create_table('test',
    sa.Column('test_col', sa.UUID(), nullable=False, comment='Первичный Ключ'),
    sa.Column('test_name', sa.String(), nullable=True, comment='Test name'),
    sa.Column('url', sa.String(), nullable=True, comment='url'),
    sa.PrimaryKeyConstraint('test_col')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.drop_table('slclass')
    # ### end Alembic commands ###
