"""add table Slclasses

Revision ID: 62b2c6eb4283
Revises: 21e285a61f08
Create Date: 2023-05-18 00:54:24.406758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62b2c6eb4283'
down_revision = '21e285a61f08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('test_col', sa.UUID(), autoincrement=False, nullable=False, comment='Первичный Ключ'),
    sa.Column('test_name', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Test name'),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True, comment='url'),
    sa.PrimaryKeyConstraint('test_col', name='test_pkey')
    )
    # ### end Alembic commands ###
