"""add url in test table

Revision ID: 70a9a100ef93
Revises: d691fa4e4bc6
Create Date: 2023-04-17 22:20:16.113465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a9a100ef93'
down_revision = 'd691fa4e4bc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('url', sa.String(), nullable=True, comment='url'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'url')
    # ### end Alembic commands ###
