"""add table Slclasses

Revision ID: 88a190697653
Revises: 0002a0ba4674
Create Date: 2023-05-18 00:38:51.873980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a190697653'
down_revision = '0002a0ba4674'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
