"""add table Slclasses

Revision ID: 9d5f8056f0ca
Revises: 62b2c6eb4283
Create Date: 2023-05-18 00:56:31.664280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d5f8056f0ca'
down_revision = '62b2c6eb4283'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slclass',
    sa.Column('cdclass', sa.UUID(), nullable=False, comment='Ключь классов'),
    sa.Column('nmclass', sa.String(), nullable=False, comment='Наименование игрального класса'),
    sa.Column('full_nmclass', sa.String(), nullable=True, comment='Полное имя класса'),
    sa.Column('url', sa.String(), nullable=True, comment='url для получения следующего обьекта класса'),
    sa.PrimaryKeyConstraint('cdclass')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slclass')
    # ### end Alembic commands ###
