"""add table Slclasses

Revision ID: a7b1022efe36
Revises: d2cd4f2188c1
Create Date: 2023-05-18 00:03:24.591384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b1022efe36'
down_revision = 'd2cd4f2188c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('test_col', sa.UUID(), nullable=False, comment='Первичный Ключ'),
    sa.Column('test_name', sa.String(), nullable=True, comment='Test name'),
    sa.Column('url', sa.String(), nullable=True, comment='url'),
    sa.PrimaryKeyConstraint('test_col')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
