"""add table Slclasses

Revision ID: c4f2f28a5d12
Revises: 23a3fb64496b
Create Date: 2023-05-18 00:36:07.173961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f2f28a5d12'
down_revision = '23a3fb64496b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
