"""add table Slclasses

Revision ID: ce1a539bce22
Revises: 4d563e358169
Create Date: 2023-05-18 00:20:53.591099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce1a539bce22'
down_revision = '4d563e358169'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
