"""add table Slclasses

Revision ID: d2cd4f2188c1
Revises: 1c12e56bc714
Create Date: 2023-05-17 23:55:31.203278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2cd4f2188c1'
down_revision = '1c12e56bc714'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
