"""add table Slclasses

Revision ID: ebf5c463aa79
Revises: f8221cf1afec
Create Date: 2023-05-18 00:06:01.827193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf5c463aa79'
down_revision = 'f8221cf1afec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
