"""add table Slclasses

Revision ID: f8221cf1afec
Revises: a7b1022efe36
Create Date: 2023-05-18 00:04:36.353356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8221cf1afec'
down_revision = 'a7b1022efe36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
